// <auto-generated />
namespace AngularSignalRMapsCharts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mc2Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mc2Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201312161154139_mc2Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
