// <auto-generated />
namespace AngularSignalRMapsCharts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mcMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mcMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201312161153025_mcMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
