// <auto-generated />
namespace LiveLog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class b1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(b1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506162128232_b1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
