<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="LiveLog.Default" %>

<!DOCTYPE html>

<html lang="en" ng-app="demoApp">
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Test of multiple frameworks">
    <meta name="author" content="Christopher Cassidy">
    <link rel="shortcut icon" href="favicon.ico">

    <title>AngularJS | SignalR | Google  Charts</title>

    <link href="/web/css/livelog.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/web/css/bootstrap-theme.css">
    <link rel="stylesheet" href="~/web/css/bootstrap.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <%--<link rel="stylesheet" href="~/web/css/animations.css">--%>

    <script src="web/js/lib/jquery/jquery-1.10.2.min.js"" ></script>
    <script src="web/js/lib/jquery/jquery-ui-1.10.3.custom.js"></script>
    
    <script src="Web/js/lib/linqjs/jquery.linq.min.js"></script>

    <script src="web/js/lib/signalr/jquery.signalR-2.0.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <%--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA52a2B7GBrLB45Bkt-Z-7IW66toW6y6Mg&sensor=false"></script>--%>
    <script type='text/javascript' src='http://www.google.com/jsapi'></script>
    <script src="Web/js/livelog.utils.js"></script>
    <script src="web/js/lib/angular/angular.js"></script>
    <script src="web/js/lib/angular/angular-animate.js"></script>
    <script src="web/js/lib/angular/angular-resource.js"></script>
    <script src="web/js/lib/angular/angular-route.js"></script>
    <script src="web/js/lib/bootstrap.js"></script>
    <script src="web/js/lib/timeago-1.0.0.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->

    <script src="web/js/app.js"></script>
    <script src="web/js/directives.js"></script>
    <script src="web/js/services.js"></script>
    <script src="web/js/filters.js"></script>
    <script src="web/js/controllers.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="default.aspx">AngularJS | SignalR | Google  Charts / Maps</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#demo">Demo</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

    <div id="wrapper">

        <div id="demo" class="cc-panel show">
            <div class="container">
                <div class="starter-template">
                    <h1>AngularJS | SignalR | Google  Charts / Maps</h1>
                    <p class="lead">This is a demo of a few different web technologies in use together.</p>
                </div>

                <div class="row well" style="margin-bottom: 30px;">
                    <h2>Demo</h2>
                    <p>This is a demonstration of real-time reporting, pushing data from the server as it's created to connected clients.  The example shows a dashboard of company analysis, displayed in three different views; a list, on a map, and a chart.</p>
                    <p>Click on the button <strong>Get more random companies</strong> to start the server creating 20 more random companies and analysis results.  As these results are created by the server, they are pushed to all connected clients viewing the page.  This simulates real-time updates and reporting from the server.  Open the page in more than one window to see it in action.</p>
                    <p>Go to the <strong>ABOUT</strong> page for details on how this magic happened.</p>
                </div>
                <div class="row view-container well">
                    <div ng-view class="view-frame"></div>
                </div>
            </div>
        </div>


        <div id="about" class="cc-panel hide">
            <div class="container">
                <div class="starter-template">
                    <h2>Frameworks at play</h2>
                    <p>SignalR is used for pushing data from the server to connected clients.  AngularJS is used on the client for binding the model data to the different views (list, map and chart).</p>
                </div>
                <div class="row well">
                    
                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail">
                            <img src="Web/images/tech/signalr-logo.png" style="max-height: 100px;" />
                            <div class="caption">
                                <h3>SignalR</h3>
                                <p>SignalR allows real-time client/server communication using one of several protocols depending on the capability of the client and server.  This allows for pushing updates to multiple clients when changes are made on the server.</p>
                                <p>
                                    <a href="http://signalr.net/">SignalR</a><br />
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail">
                            <img src="Web/images/tech/angularjs-logo.png" />
                            <div class="caption">
                                <h3>Angular.js</h3>
                                <p>I use Angular.js to build an MVC style javascript framework, allowing the binding of business objects to client views, and presisting changes to the model client side to the server.</p>
                                <p>AngularJS is also used for linking events between the list, chart and maps, so that focus is set on each when one is selected.</p>                                
                                <p>
                                    <a href="http://angularjs.org">Angular.js</a><br />
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail">
                            <img src="Web/images/tech/google-maps-logo.png" style="max-height: 50px; display: inline-table; margin-left: 50px;" />
                            <img src="Web/images/tech/google-charts-logo.png" style="max-height: 50px; display: inline-table; margin-left: 25px;" />
                            <div class="caption">
                                <h3>Google Maps and Charts</h3>
                                <p>I use thre Google Charts and Maps API for displaying the data in a few different ways.  I map the location of the company (by post code), and chart the results as they are sent by ther server on a timeline chart.</p>  
                                <p><a href="https://developers.google.com/chart/">Google Charts</a></p>
                                <p><a href="https://developers.google.com/maps/">Googler Maps</a></p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail">
                            <img src="Web/images/tech/wcf-logo.jpg" style="max-height: 160px; height: 43px;" />
                            <img src="web/images/tech/ef-logo.jpg" style="max-height: 160px;">
                            <div class="caption">
                                <h3>EF and WCF</h3>
                                <p>I use WCF to build RESTful web services for client-server communications through an API.  This enables AngularJS to presist models to the server/database.</p>
                                <p>Entity Framework provides the data-object persistence layer in the application.  This removes the need for building lower level data access components and business object mappings.</p>
                                <p><a href="http://msdn.microsoft.com/en-us/data/ef.aspx">Entity Framework</a></p>
                                <p><a href="http://msdn.microsoft.com/en-us/library/ms731082.aspx">Windows Communiaction Foundation</a></p>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div id="contact" class="cc-panel hide">
            <div class="container">
                <div class="starter-template">
                    <h2>Get in contact</h2>
                </div>
                <div class="row well">
                    <div class="col-sm-6 col-md-3 col-md-offset-3">
                        <div class="thumbnail">
                            <img src="Web/images/chris-profile.jpg" style="max-height: 240px;" />
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <p><span class="glyphicon glyphicon-user"></span>Christopher Cassidy</p>
                        <p><span class="glyphicon glyphicon-send"></span><a href="mailto:hello@christopher-cassidy.cc" target="_blank">hello@christopher-cassidy.cc</a></p>
                        <p><span class="glyphicon glyphicon-globe"></span><a href="http://www.christopher-cassidy.cc" target="_blank">www.christopher-cassidy.cc</a></p>
                        <p>
                            <br />
                            <br />
                            <br />
                            <small>&copy; 2013  |  Christopher Cassidy.</small></p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            
            $('.cc-panel.hide').css({ 'left': '100%' }).removeClass('hide');

            //bind events
            $('.nav a').on('click', function (event) {
                event.preventDefault();

                $(this).parent().parent().find('li.active').removeClass('active');
                $(this).parent().addClass('active');

                var id = $(this).attr('href');
                $('.cc-panel.show').stop(true, true).animate({ 'left': '-100%' }, 1000, function () { $(this).css({ 'left': '100%' }).removeClass('show'); });
                $(id).stop(true, true).animate({ 'left': '0%' }, 1000, function () { $(this).addClass('show'); });
                //$(id).show('slide', { direction: 'right' }, 3000, function () { $(this).addClass('show'); });
            });
        });
    </script>
</body>
</html>
